version: '3.5'
services:

  traefik:
    image: traefik:3.1.1
    container_name: ${FAERING_PROJECT_NAME:-faering}_traefik
    environment:
      TRAEFIK_API: 'true'
      TRAEFIK_API_DASHBOARD: 'true'
      TRAEFIK_API_DISABLEDASHBOARDAD: 'true'
      TRAEFIK_API_DEBUG: ${FAERING_DEBUG:-false}
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ':${FAERING_HTTP_PORT:-80}'
      TRAEFIK_ENTRYPOINTS_HTTPS: 'true'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ':${FAERING_HTTPS_PORT:-443}'
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS: 'true'
      TRAEFIK_GLOBAL_CHECKNEWVERSION: 'false'
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: 'false'
      TRAEFIK_LOG_LEVEL: ERROR
      TRAEFIK_PROVIDERS_DOCKER: 'true'
      TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE: Host(`{{ normalize .Name }}.${FAERING_PROJECT_DOMAIN:-docker.test}`)
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: ${FAERING_NETWORK:-faering}
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: /etc/traefik/dynamic/
      TRAEFIK_SERVERSTRANSPORT_ROOTCAS: /certs/faering.rootCA.crt
    restart: always
    ports:
      - '${FAERING_HTTP_PORT:-80}:80'
      - '${FAERING_HTTPS_PORT:-443}:443'
    volumes:
      - ./config/traefik.yml:/etc/traefik/dynamic/faering.yml
      - ./certificates/${FAERING_PROJECT_DOMAIN:-docker.test}.rootCA.crt:/certs/faering.rootCA.crt:ro
      - ./certificates/${FAERING_PROJECT_DOMAIN:-docker.test}.crt:/certs/faering.crt:ro
      - ./certificates/${FAERING_PROJECT_DOMAIN:-docker.test}.key:/certs/faering.key:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${FAERING_PROJECT_NAME:-faering}_traefik.rule=Host(`traefik.${FAERING_PROJECT_DOMAIN:-docker.test}`)'
      - 'traefik.http.services.${FAERING_PROJECT_NAME:-faering}_traefik.loadbalancer.server.port=8080'
    networks:
      - faering

  portainer:
    image: portainer/portainer-ce:2.20.3-alpine
    container_name: ${FAERING_PROJECT_NAME:-faering}_portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock --admin-password=${FAERING_PORTAINER_PASSWORD} --no-analytics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${FAERING_PROJECT_NAME:-faering}_portainer.rule=Host(`portainer.${FAERING_PROJECT_DOMAIN:-docker.test}`)'
      - 'traefik.http.services.${FAERING_PROJECT_NAME:-faering}_portainer.loadbalancer.server.port=9000'
    networks:
      - faering

networks:
  faering:
    name: ${FAERING_NETWORK:-faering}
